//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace ReadFileConsoleApp.localhost1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback createEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback searchEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback populateEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMetaDataEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEmployeeAndRelativesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEmployeeSickYear2004OperationCompleted;
        
        private System.Threading.SendOrPostCallback getMostSickEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMetaDataAllKeysOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMetaDataAllIndexOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMetaDataAllTableConstraintsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMetaDataAllTables1OperationCompleted;
        
        private System.Threading.SendOrPostCallback getMetaDataAllTables2OperationCompleted;
        
        private System.Threading.SendOrPostCallback getMetaDataAllColumnsEmployee1OperationCompleted;
        
        private System.Threading.SendOrPostCallback getMetaDataAllColumnsEmployee2OperationCompleted;
        
        private System.Threading.SendOrPostCallback filePathOperationCompleted;
        
        private System.Threading.SendOrPostCallback getTablesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::ReadFileConsoleApp.Properties.Settings.Default.ReadFileConsoleApp_localhost1_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event createEmployeeCompletedEventHandler createEmployeeCompleted;
        
        /// <remarks/>
        public event updateEmployeeCompletedEventHandler updateEmployeeCompleted;
        
        /// <remarks/>
        public event searchEmployeeCompletedEventHandler searchEmployeeCompleted;
        
        /// <remarks/>
        public event populateEmployeeCompletedEventHandler populateEmployeeCompleted;
        
        /// <remarks/>
        public event deleteEmployeeCompletedEventHandler deleteEmployeeCompleted;
        
        /// <remarks/>
        public event getMetaDataEmployeeCompletedEventHandler getMetaDataEmployeeCompleted;
        
        /// <remarks/>
        public event getEmployeeAndRelativesCompletedEventHandler getEmployeeAndRelativesCompleted;
        
        /// <remarks/>
        public event getEmployeeSickYear2004CompletedEventHandler getEmployeeSickYear2004Completed;
        
        /// <remarks/>
        public event getMostSickEmployeeCompletedEventHandler getMostSickEmployeeCompleted;
        
        /// <remarks/>
        public event getMetaDataAllKeysCompletedEventHandler getMetaDataAllKeysCompleted;
        
        /// <remarks/>
        public event getMetaDataAllIndexCompletedEventHandler getMetaDataAllIndexCompleted;
        
        /// <remarks/>
        public event getMetaDataAllTableConstraintsCompletedEventHandler getMetaDataAllTableConstraintsCompleted;
        
        /// <remarks/>
        public event getMetaDataAllTables1CompletedEventHandler getMetaDataAllTables1Completed;
        
        /// <remarks/>
        public event getMetaDataAllTables2CompletedEventHandler getMetaDataAllTables2Completed;
        
        /// <remarks/>
        public event getMetaDataAllColumnsEmployee1CompletedEventHandler getMetaDataAllColumnsEmployee1Completed;
        
        /// <remarks/>
        public event getMetaDataAllColumnsEmployee2CompletedEventHandler getMetaDataAllColumnsEmployee2Completed;
        
        /// <remarks/>
        public event filePathCompletedEventHandler filePathCompleted;
        
        /// <remarks/>
        public event getTablesCompletedEventHandler getTablesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/createEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void createEmployee(string[] EmployeeData) {
            this.Invoke("createEmployee", new object[] {
                        EmployeeData});
        }
        
        /// <remarks/>
        public void createEmployeeAsync(string[] EmployeeData) {
            this.createEmployeeAsync(EmployeeData, null);
        }
        
        /// <remarks/>
        public void createEmployeeAsync(string[] EmployeeData, object userState) {
            if ((this.createEmployeeOperationCompleted == null)) {
                this.createEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateEmployeeOperationCompleted);
            }
            this.InvokeAsync("createEmployee", new object[] {
                        EmployeeData}, this.createEmployeeOperationCompleted, userState);
        }
        
        private void OncreateEmployeeOperationCompleted(object arg) {
            if ((this.createEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createEmployeeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateEmployee(string[] EmployeeData) {
            this.Invoke("updateEmployee", new object[] {
                        EmployeeData});
        }
        
        /// <remarks/>
        public void updateEmployeeAsync(string[] EmployeeData) {
            this.updateEmployeeAsync(EmployeeData, null);
        }
        
        /// <remarks/>
        public void updateEmployeeAsync(string[] EmployeeData, object userState) {
            if ((this.updateEmployeeOperationCompleted == null)) {
                this.updateEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateEmployeeOperationCompleted);
            }
            this.InvokeAsync("updateEmployee", new object[] {
                        EmployeeData}, this.updateEmployeeOperationCompleted, userState);
        }
        
        private void OnupdateEmployeeOperationCompleted(object arg) {
            if ((this.updateEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateEmployeeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/searchEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Employee[] searchEmployee(string SearchString) {
            object[] results = this.Invoke("searchEmployee", new object[] {
                        SearchString});
            return ((Employee[])(results[0]));
        }
        
        /// <remarks/>
        public void searchEmployeeAsync(string SearchString) {
            this.searchEmployeeAsync(SearchString, null);
        }
        
        /// <remarks/>
        public void searchEmployeeAsync(string SearchString, object userState) {
            if ((this.searchEmployeeOperationCompleted == null)) {
                this.searchEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchEmployeeOperationCompleted);
            }
            this.InvokeAsync("searchEmployee", new object[] {
                        SearchString}, this.searchEmployeeOperationCompleted, userState);
        }
        
        private void OnsearchEmployeeOperationCompleted(object arg) {
            if ((this.searchEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchEmployeeCompleted(this, new searchEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/populateEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Employee[] populateEmployee(string EmployeeSsn) {
            object[] results = this.Invoke("populateEmployee", new object[] {
                        EmployeeSsn});
            return ((Employee[])(results[0]));
        }
        
        /// <remarks/>
        public void populateEmployeeAsync(string EmployeeSsn) {
            this.populateEmployeeAsync(EmployeeSsn, null);
        }
        
        /// <remarks/>
        public void populateEmployeeAsync(string EmployeeSsn, object userState) {
            if ((this.populateEmployeeOperationCompleted == null)) {
                this.populateEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpopulateEmployeeOperationCompleted);
            }
            this.InvokeAsync("populateEmployee", new object[] {
                        EmployeeSsn}, this.populateEmployeeOperationCompleted, userState);
        }
        
        private void OnpopulateEmployeeOperationCompleted(object arg) {
            if ((this.populateEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.populateEmployeeCompleted(this, new populateEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/deleteEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deleteEmployee(string EmployeeSsn) {
            this.Invoke("deleteEmployee", new object[] {
                        EmployeeSsn});
        }
        
        /// <remarks/>
        public void deleteEmployeeAsync(string EmployeeSsn) {
            this.deleteEmployeeAsync(EmployeeSsn, null);
        }
        
        /// <remarks/>
        public void deleteEmployeeAsync(string EmployeeSsn, object userState) {
            if ((this.deleteEmployeeOperationCompleted == null)) {
                this.deleteEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteEmployeeOperationCompleted);
            }
            this.InvokeAsync("deleteEmployee", new object[] {
                        EmployeeSsn}, this.deleteEmployeeOperationCompleted, userState);
        }
        
        private void OndeleteEmployeeOperationCompleted(object arg) {
            if ((this.deleteEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteEmployeeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getMetaDataEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Employee[] getMetaDataEmployee() {
            object[] results = this.Invoke("getMetaDataEmployee", new object[0]);
            return ((Employee[])(results[0]));
        }
        
        /// <remarks/>
        public void getMetaDataEmployeeAsync() {
            this.getMetaDataEmployeeAsync(null);
        }
        
        /// <remarks/>
        public void getMetaDataEmployeeAsync(object userState) {
            if ((this.getMetaDataEmployeeOperationCompleted == null)) {
                this.getMetaDataEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMetaDataEmployeeOperationCompleted);
            }
            this.InvokeAsync("getMetaDataEmployee", new object[0], this.getMetaDataEmployeeOperationCompleted, userState);
        }
        
        private void OngetMetaDataEmployeeOperationCompleted(object arg) {
            if ((this.getMetaDataEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMetaDataEmployeeCompleted(this, new getMetaDataEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getEmployeeAndRelatives", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Emprelative[] getEmployeeAndRelatives() {
            object[] results = this.Invoke("getEmployeeAndRelatives", new object[0]);
            return ((Emprelative[])(results[0]));
        }
        
        /// <remarks/>
        public void getEmployeeAndRelativesAsync() {
            this.getEmployeeAndRelativesAsync(null);
        }
        
        /// <remarks/>
        public void getEmployeeAndRelativesAsync(object userState) {
            if ((this.getEmployeeAndRelativesOperationCompleted == null)) {
                this.getEmployeeAndRelativesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEmployeeAndRelativesOperationCompleted);
            }
            this.InvokeAsync("getEmployeeAndRelatives", new object[0], this.getEmployeeAndRelativesOperationCompleted, userState);
        }
        
        private void OngetEmployeeAndRelativesOperationCompleted(object arg) {
            if ((this.getEmployeeAndRelativesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEmployeeAndRelativesCompleted(this, new getEmployeeAndRelativesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getEmployeeSickYear2004", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SickEmp[] getEmployeeSickYear2004() {
            object[] results = this.Invoke("getEmployeeSickYear2004", new object[0]);
            return ((SickEmp[])(results[0]));
        }
        
        /// <remarks/>
        public void getEmployeeSickYear2004Async() {
            this.getEmployeeSickYear2004Async(null);
        }
        
        /// <remarks/>
        public void getEmployeeSickYear2004Async(object userState) {
            if ((this.getEmployeeSickYear2004OperationCompleted == null)) {
                this.getEmployeeSickYear2004OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEmployeeSickYear2004OperationCompleted);
            }
            this.InvokeAsync("getEmployeeSickYear2004", new object[0], this.getEmployeeSickYear2004OperationCompleted, userState);
        }
        
        private void OngetEmployeeSickYear2004OperationCompleted(object arg) {
            if ((this.getEmployeeSickYear2004Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEmployeeSickYear2004Completed(this, new getEmployeeSickYear2004CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getMostSickEmployee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SickEmp[] getMostSickEmployee() {
            object[] results = this.Invoke("getMostSickEmployee", new object[0]);
            return ((SickEmp[])(results[0]));
        }
        
        /// <remarks/>
        public void getMostSickEmployeeAsync() {
            this.getMostSickEmployeeAsync(null);
        }
        
        /// <remarks/>
        public void getMostSickEmployeeAsync(object userState) {
            if ((this.getMostSickEmployeeOperationCompleted == null)) {
                this.getMostSickEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMostSickEmployeeOperationCompleted);
            }
            this.InvokeAsync("getMostSickEmployee", new object[0], this.getMostSickEmployeeOperationCompleted, userState);
        }
        
        private void OngetMostSickEmployeeOperationCompleted(object arg) {
            if ((this.getMostSickEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMostSickEmployeeCompleted(this, new getMostSickEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getMetaDataAllKeys", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MetaData[] getMetaDataAllKeys() {
            object[] results = this.Invoke("getMetaDataAllKeys", new object[0]);
            return ((MetaData[])(results[0]));
        }
        
        /// <remarks/>
        public void getMetaDataAllKeysAsync() {
            this.getMetaDataAllKeysAsync(null);
        }
        
        /// <remarks/>
        public void getMetaDataAllKeysAsync(object userState) {
            if ((this.getMetaDataAllKeysOperationCompleted == null)) {
                this.getMetaDataAllKeysOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMetaDataAllKeysOperationCompleted);
            }
            this.InvokeAsync("getMetaDataAllKeys", new object[0], this.getMetaDataAllKeysOperationCompleted, userState);
        }
        
        private void OngetMetaDataAllKeysOperationCompleted(object arg) {
            if ((this.getMetaDataAllKeysCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMetaDataAllKeysCompleted(this, new getMetaDataAllKeysCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getMetaDataAllIndex", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MetaData[] getMetaDataAllIndex() {
            object[] results = this.Invoke("getMetaDataAllIndex", new object[0]);
            return ((MetaData[])(results[0]));
        }
        
        /// <remarks/>
        public void getMetaDataAllIndexAsync() {
            this.getMetaDataAllIndexAsync(null);
        }
        
        /// <remarks/>
        public void getMetaDataAllIndexAsync(object userState) {
            if ((this.getMetaDataAllIndexOperationCompleted == null)) {
                this.getMetaDataAllIndexOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMetaDataAllIndexOperationCompleted);
            }
            this.InvokeAsync("getMetaDataAllIndex", new object[0], this.getMetaDataAllIndexOperationCompleted, userState);
        }
        
        private void OngetMetaDataAllIndexOperationCompleted(object arg) {
            if ((this.getMetaDataAllIndexCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMetaDataAllIndexCompleted(this, new getMetaDataAllIndexCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getMetaDataAllTableConstraints", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MetaData[] getMetaDataAllTableConstraints() {
            object[] results = this.Invoke("getMetaDataAllTableConstraints", new object[0]);
            return ((MetaData[])(results[0]));
        }
        
        /// <remarks/>
        public void getMetaDataAllTableConstraintsAsync() {
            this.getMetaDataAllTableConstraintsAsync(null);
        }
        
        /// <remarks/>
        public void getMetaDataAllTableConstraintsAsync(object userState) {
            if ((this.getMetaDataAllTableConstraintsOperationCompleted == null)) {
                this.getMetaDataAllTableConstraintsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMetaDataAllTableConstraintsOperationCompleted);
            }
            this.InvokeAsync("getMetaDataAllTableConstraints", new object[0], this.getMetaDataAllTableConstraintsOperationCompleted, userState);
        }
        
        private void OngetMetaDataAllTableConstraintsOperationCompleted(object arg) {
            if ((this.getMetaDataAllTableConstraintsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMetaDataAllTableConstraintsCompleted(this, new getMetaDataAllTableConstraintsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getMetaDataAllTables1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MetaData[] getMetaDataAllTables1() {
            object[] results = this.Invoke("getMetaDataAllTables1", new object[0]);
            return ((MetaData[])(results[0]));
        }
        
        /// <remarks/>
        public void getMetaDataAllTables1Async() {
            this.getMetaDataAllTables1Async(null);
        }
        
        /// <remarks/>
        public void getMetaDataAllTables1Async(object userState) {
            if ((this.getMetaDataAllTables1OperationCompleted == null)) {
                this.getMetaDataAllTables1OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMetaDataAllTables1OperationCompleted);
            }
            this.InvokeAsync("getMetaDataAllTables1", new object[0], this.getMetaDataAllTables1OperationCompleted, userState);
        }
        
        private void OngetMetaDataAllTables1OperationCompleted(object arg) {
            if ((this.getMetaDataAllTables1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMetaDataAllTables1Completed(this, new getMetaDataAllTables1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getMetaDataAllTables2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MetaData[] getMetaDataAllTables2() {
            object[] results = this.Invoke("getMetaDataAllTables2", new object[0]);
            return ((MetaData[])(results[0]));
        }
        
        /// <remarks/>
        public void getMetaDataAllTables2Async() {
            this.getMetaDataAllTables2Async(null);
        }
        
        /// <remarks/>
        public void getMetaDataAllTables2Async(object userState) {
            if ((this.getMetaDataAllTables2OperationCompleted == null)) {
                this.getMetaDataAllTables2OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMetaDataAllTables2OperationCompleted);
            }
            this.InvokeAsync("getMetaDataAllTables2", new object[0], this.getMetaDataAllTables2OperationCompleted, userState);
        }
        
        private void OngetMetaDataAllTables2OperationCompleted(object arg) {
            if ((this.getMetaDataAllTables2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMetaDataAllTables2Completed(this, new getMetaDataAllTables2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getMetaDataAllColumnsEmployee1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MetaData[] getMetaDataAllColumnsEmployee1() {
            object[] results = this.Invoke("getMetaDataAllColumnsEmployee1", new object[0]);
            return ((MetaData[])(results[0]));
        }
        
        /// <remarks/>
        public void getMetaDataAllColumnsEmployee1Async() {
            this.getMetaDataAllColumnsEmployee1Async(null);
        }
        
        /// <remarks/>
        public void getMetaDataAllColumnsEmployee1Async(object userState) {
            if ((this.getMetaDataAllColumnsEmployee1OperationCompleted == null)) {
                this.getMetaDataAllColumnsEmployee1OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMetaDataAllColumnsEmployee1OperationCompleted);
            }
            this.InvokeAsync("getMetaDataAllColumnsEmployee1", new object[0], this.getMetaDataAllColumnsEmployee1OperationCompleted, userState);
        }
        
        private void OngetMetaDataAllColumnsEmployee1OperationCompleted(object arg) {
            if ((this.getMetaDataAllColumnsEmployee1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMetaDataAllColumnsEmployee1Completed(this, new getMetaDataAllColumnsEmployee1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getMetaDataAllColumnsEmployee2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MetaData[] getMetaDataAllColumnsEmployee2() {
            object[] results = this.Invoke("getMetaDataAllColumnsEmployee2", new object[0]);
            return ((MetaData[])(results[0]));
        }
        
        /// <remarks/>
        public void getMetaDataAllColumnsEmployee2Async() {
            this.getMetaDataAllColumnsEmployee2Async(null);
        }
        
        /// <remarks/>
        public void getMetaDataAllColumnsEmployee2Async(object userState) {
            if ((this.getMetaDataAllColumnsEmployee2OperationCompleted == null)) {
                this.getMetaDataAllColumnsEmployee2OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMetaDataAllColumnsEmployee2OperationCompleted);
            }
            this.InvokeAsync("getMetaDataAllColumnsEmployee2", new object[0], this.getMetaDataAllColumnsEmployee2OperationCompleted, userState);
        }
        
        private void OngetMetaDataAllColumnsEmployee2OperationCompleted(object arg) {
            if ((this.getMetaDataAllColumnsEmployee2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMetaDataAllColumnsEmployee2Completed(this, new getMetaDataAllColumnsEmployee2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/filePath", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] filePath(string answer) {
            object[] results = this.Invoke("filePath", new object[] {
                        answer});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void filePathAsync(string answer) {
            this.filePathAsync(answer, null);
        }
        
        /// <remarks/>
        public void filePathAsync(string answer, object userState) {
            if ((this.filePathOperationCompleted == null)) {
                this.filePathOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfilePathOperationCompleted);
            }
            this.InvokeAsync("filePath", new object[] {
                        answer}, this.filePathOperationCompleted, userState);
        }
        
        private void OnfilePathOperationCompleted(object arg) {
            if ((this.filePathCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.filePathCompleted(this, new filePathCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getTables", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public QueryResult[] getTables() {
            object[] results = this.Invoke("getTables", new object[0]);
            return ((QueryResult[])(results[0]));
        }
        
        /// <remarks/>
        public void getTablesAsync() {
            this.getTablesAsync(null);
        }
        
        /// <remarks/>
        public void getTablesAsync(object userState) {
            if ((this.getTablesOperationCompleted == null)) {
                this.getTablesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetTablesOperationCompleted);
            }
            this.InvokeAsync("getTables", new object[0], this.getTablesOperationCompleted, userState);
        }
        
        private void OngetTablesOperationCompleted(object arg) {
            if ((this.getTablesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getTablesCompleted(this, new getTablesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Employee {
        
        private string firstnameField;
        
        private string employeeNoField;
        
        private string lastnameField;
        
        private string jobTitleField;
        
        private string addressField;
        
        private string cityField;
        
        private string postCodeField;
        
        private string phoneNoField;
        
        private string mobilePhoneNoField;
        
        private string emailField;
        
        private string socialSecurityNoField;
        
        private string unionMembershipNoField;
        
        private string sexField;
        
        /// <remarks/>
        public string Firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        public string EmployeeNo {
            get {
                return this.employeeNoField;
            }
            set {
                this.employeeNoField = value;
            }
        }
        
        /// <remarks/>
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        public string JobTitle {
            get {
                return this.jobTitleField;
            }
            set {
                this.jobTitleField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNo {
            get {
                return this.phoneNoField;
            }
            set {
                this.phoneNoField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePhoneNo {
            get {
                return this.mobilePhoneNoField;
            }
            set {
                this.mobilePhoneNoField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string SocialSecurityNo {
            get {
                return this.socialSecurityNoField;
            }
            set {
                this.socialSecurityNoField = value;
            }
        }
        
        /// <remarks/>
        public string UnionMembershipNo {
            get {
                return this.unionMembershipNoField;
            }
            set {
                this.unionMembershipNoField = value;
            }
        }
        
        /// <remarks/>
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class QueryResult {
        
        private string nameField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MetaData {
        
        private string index1Field;
        
        private string index2Field;
        
        private string index3Field;
        
        private string index4Field;
        
        /// <remarks/>
        public string index1 {
            get {
                return this.index1Field;
            }
            set {
                this.index1Field = value;
            }
        }
        
        /// <remarks/>
        public string index2 {
            get {
                return this.index2Field;
            }
            set {
                this.index2Field = value;
            }
        }
        
        /// <remarks/>
        public string index3 {
            get {
                return this.index3Field;
            }
            set {
                this.index3Field = value;
            }
        }
        
        /// <remarks/>
        public string index4 {
            get {
                return this.index4Field;
            }
            set {
                this.index4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SickEmp {
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string employeeNoField;
        
        private string quantityField;
        
        /// <remarks/>
        public string Firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        public string EmployeeNo {
            get {
                return this.employeeNoField;
            }
            set {
                this.employeeNoField = value;
            }
        }
        
        /// <remarks/>
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Emprelative {
        
        private string firstnameField;
        
        private string lastnameField;
        
        private string jobTitleField;
        
        private string employeeNoField;
        
        private string relativecodeField;
        
        private string firstnameRelativeField;
        
        private string lastnameRelativeField;
        
        /// <remarks/>
        public string Firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        public string Lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        public string JobTitle {
            get {
                return this.jobTitleField;
            }
            set {
                this.jobTitleField = value;
            }
        }
        
        /// <remarks/>
        public string EmployeeNo {
            get {
                return this.employeeNoField;
            }
            set {
                this.employeeNoField = value;
            }
        }
        
        /// <remarks/>
        public string Relativecode {
            get {
                return this.relativecodeField;
            }
            set {
                this.relativecodeField = value;
            }
        }
        
        /// <remarks/>
        public string FirstnameRelative {
            get {
                return this.firstnameRelativeField;
            }
            set {
                this.firstnameRelativeField = value;
            }
        }
        
        /// <remarks/>
        public string LastnameRelative {
            get {
                return this.lastnameRelativeField;
            }
            set {
                this.lastnameRelativeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void createEmployeeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void updateEmployeeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void searchEmployeeCompletedEventHandler(object sender, searchEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Employee[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Employee[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void populateEmployeeCompletedEventHandler(object sender, populateEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class populateEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal populateEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Employee[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Employee[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void deleteEmployeeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getMetaDataEmployeeCompletedEventHandler(object sender, getMetaDataEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMetaDataEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMetaDataEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Employee[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Employee[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getEmployeeAndRelativesCompletedEventHandler(object sender, getEmployeeAndRelativesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEmployeeAndRelativesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEmployeeAndRelativesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Emprelative[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Emprelative[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getEmployeeSickYear2004CompletedEventHandler(object sender, getEmployeeSickYear2004CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEmployeeSickYear2004CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEmployeeSickYear2004CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SickEmp[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SickEmp[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getMostSickEmployeeCompletedEventHandler(object sender, getMostSickEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMostSickEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMostSickEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SickEmp[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SickEmp[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getMetaDataAllKeysCompletedEventHandler(object sender, getMetaDataAllKeysCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMetaDataAllKeysCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMetaDataAllKeysCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MetaData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MetaData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getMetaDataAllIndexCompletedEventHandler(object sender, getMetaDataAllIndexCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMetaDataAllIndexCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMetaDataAllIndexCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MetaData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MetaData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getMetaDataAllTableConstraintsCompletedEventHandler(object sender, getMetaDataAllTableConstraintsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMetaDataAllTableConstraintsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMetaDataAllTableConstraintsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MetaData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MetaData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getMetaDataAllTables1CompletedEventHandler(object sender, getMetaDataAllTables1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMetaDataAllTables1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMetaDataAllTables1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MetaData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MetaData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getMetaDataAllTables2CompletedEventHandler(object sender, getMetaDataAllTables2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMetaDataAllTables2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMetaDataAllTables2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MetaData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MetaData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getMetaDataAllColumnsEmployee1CompletedEventHandler(object sender, getMetaDataAllColumnsEmployee1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMetaDataAllColumnsEmployee1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMetaDataAllColumnsEmployee1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MetaData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MetaData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getMetaDataAllColumnsEmployee2CompletedEventHandler(object sender, getMetaDataAllColumnsEmployee2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMetaDataAllColumnsEmployee2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMetaDataAllColumnsEmployee2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MetaData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MetaData[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void filePathCompletedEventHandler(object sender, filePathCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class filePathCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal filePathCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getTablesCompletedEventHandler(object sender, getTablesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getTablesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getTablesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QueryResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QueryResult[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591